//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VT.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPorfolio
    {
        public int Id { get; set; }
        public string SkillTitle { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> DemoId { get; set; }
    }
}
